name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: vcpkg ports
      run: cp -r vcpkg/ports $VCPKG_INSTALLATION_ROOT
    - name: vcpkg cache
      id: vcpkg-cache
      uses: actions/cache@v1
      with:
        path: vcpkg-installed
        key: vcpkg-installed-${{ runner.os }}-${{ hashFiles('vcpkg/**') }}
    - name: vcpkg cache init
      if: steps.vcpkg-cache.outputs.cache-hit != 'true'
      run: |
        ln -s $VCPKG_INSTALLATION_ROOT/installed vcpkg-installed
        vcpkg install $(cat vcpkg/VCPKG_DEPS_LIST)
    - name: vcpkg cache apply
      if: steps.vcpkg-cache.outputs.cache-hit == 'true'
      run: |
        rm -rf $VCPKG_INSTALLATION_ROOT/installed
        ln -s `pwd`/vcpkg-installed $VCPKG_INSTALLATION_ROOT/installed
    - name: cmake
      run: cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake
    - name: build
      run: |
        cmake --build build -- -j2
        mkdir build/artifact
        cp build/graphiql.html build/src/bcx build/artifact
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: bcx
        path: build/artifact
