name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: vcpkg ports
      run: cp -r vcpkg/ports $VCPKG_INSTALLATION_ROOT
    - name: vcpkg cache
      id: vcpkg-cache
      uses: actions/cache@v1
      with:
        path: vcpkg-installed
        key: vcpkg-installed-${{ runner.os }}-${{ hashFiles('vcpkg/**') }}
    - name: vcpkg cache init
      if: steps.vcpkg-cache.outputs.cache-hit != 'true'
      run: ln -s $VCPKG_INSTALLATION_ROOT/installed vcpkg-installed
    - name: vcpkg cache apply
      if: steps.vcpkg-cache.outputs.cache-hit == 'true'
      run: |
        rm -rf $VCPKG_INSTALLATION_ROOT/installed
        ln -s `pwd`/vcpkg-installed $VCPKG_INSTALLATION_ROOT/installed
    - name: vcpkg install
      run: vcpkg install $(cat vcpkg/VCPKG_DEPS_LIST)
